services:
  postgres:
    container_name: whispia-postgresql
    environment:
      POSTGRES_USER: whispia
      POSTGRES_PASSWORD: whispia
      POSTGRES_DB: whispia
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U whispia -d whispia" ]
      interval: 30s
      timeout: 1s
      retries: 5

volumes:
  pg-data: