services:
  postgres:
    container_name: whispia-postgresql
    environment:
      POSTGRES_USER: whispia
      POSTGRES_PASSWORD: whispia
      POSTGRES_DB: whispia
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U whispia -d whispia" ]
      interval: 30s
      timeout: 1s
      retries: 5

  redis:
    container_name: whispia-redis
    image: redis:8.2.1-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
      - ./config/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  sonarqube-postgres:
    container_name: whispia-sonarqube-postgresql
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    image: postgres:16
    ports:
      - "5434:5432"
    volumes:
      - sonar-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonarqube -d sonarqube" ]
      interval: 30s
      timeout: 1s
      retries: 5

  # ./gradlew clean test jacocoTestReport sonar -Dsonar.token=your_token_here
  sonarqube:
    container_name: whispia-sonarqube
    image: sonarqube:25.8.0.112029-community
    ports:
      - "9001:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
      SONAR_CE_JAVAOPTS: "-Xmx1g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
      SONAR_WEB_JAVAOPTS: "-Xmx1g -Xms512m -XX:+UseG1GC"
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar-logs:/opt/sonarqube/logs
    depends_on:
      sonarqube-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/system/status | grep -q UP"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          cpus: '1.0'
          memory: 2G

  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.5
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - ./logs:/app-logs
      - ./config/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

volumes:
  pg-data:
  sonar-pg-data:
  sonar-data:
  sonar-extensions:
  sonar-logs:
  grafana-data:
  redis-data: