spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/whispia
    username: whispia
    password: whispia

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    # 뷰 렌더링 중 JPA 세션 열림 비활성화
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/db.changelog-master.yaml
    contexts: local