server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-server
          __path__: /app-logs/api-server.log

  - job_name: chat-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: chat-server
          __path__: /app-logs/chat-server.log
